loan:
  amount:
    min: 10
    max: 999
  term-range:
    min: 10
    max: 100
  off-hours:
    start: 00:00
    stop: 06:00
  interest: 0.1
  extension-term: 20

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

invalid:
  data:
    message: Invalid arguments found {}

